# Generated by Django 5.0.6 on 2025-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskElectricalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.CharField(default='14.04.2025', max_length=10, verbose_name='дата создания')),
                ('date_registration', models.CharField(default='14.04.2025', max_length=10, verbose_name='дата заявки')),
                ('date_execution', models.CharField(max_length=10, verbose_name='дата выполнения')),
                ('city', models.CharField(default='Сегежа', max_length=250, verbose_name='город')),
                ('street', models.CharField(max_length=250, verbose_name='улица')),
                ('house', models.CharField(max_length=10, verbose_name='номер дома')),
                ('apartment', models.CharField(max_length=10, verbose_name='квартира')),
                ('task', models.TextField(verbose_name='заявка')),
                ('complited_work', models.TextField(verbose_name='выполенные работы')),
                ('materials_used', models.TextField(verbose_name='материалы')),
                ('payment_amount', models.FloatField(default=0.0, verbose_name='сумма оплаты')),
                ('note', models.TextField(verbose_name='примечания')),
            ],
        ),
    ]
