# Generated by Django 5.0.6 on 2025-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_execution',
            field=models.CharField(blank=True, max_length=10, verbose_name='дата выполнения'),
        ),
    ]
