# Generated by Django 5.0.6 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0002_alter_taskelectricalmodel_date_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='complited_work',
            field=models.TextField(blank=True, verbose_name='выполенные работы'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='materials_used',
            field=models.TextField(blank=True, verbose_name='материалы'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='note',
            field=models.TextField(blank=True, verbose_name='примечания'),
        ),
    ]
