# Generated by Django 5.0.6 on 2025-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0003_alter_taskelectricalmodel_apartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskelectricalmodel',
            options={'verbose_name': 'Заявка на работу', 'verbose_name_plural': 'Заявки на работы'},
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_creation',
            field=models.CharField(default='27.04.2025', max_length=10, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_registration',
            field=models.CharField(default='27.04.2025', max_length=10, verbose_name='дата заявки'),
        ),
    ]
