# Generated by Django 5.0.6 on 2025-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0004_alter_taskelectricalmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskelectricalmodel',
            options={'ordering': ['-pk'], 'verbose_name': 'Заявка на работу', 'verbose_name_plural': 'Заявки на работы'},
        ),
        migrations.AddField(
            model_name='taskelectricalmodel',
            name='date_deadline',
            field=models.CharField(blank=True, max_length=10, verbose_name='дата выполнения'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_creation',
            field=models.CharField(default='03.06.2025', max_length=10, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_registration',
            field=models.CharField(default='03.06.2025', max_length=10, verbose_name='дата заявки'),
        ),
    ]
