# Generated by Django 5.0.6 on 2025-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0005_alter_taskelectricalmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_creation',
            field=models.CharField(default='07.06.2025', max_length=10, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_execution',
            field=models.CharField(blank=True, default='07.06.2025', max_length=10, verbose_name='дата выполнения'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_registration',
            field=models.CharField(blank=True, default='07.06.2025', max_length=10, verbose_name='дата заявки'),
        ),
    ]
