# Generated by Django 5.0.6 on 2025-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0009_alter_taskelectricalmodel_date_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_execution',
            field=models.CharField(default='07.06.2025', max_length=10, verbose_name='дата выполнения'),
        ),
    ]
