# Generated by Django 5.0.6 on 2025-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0013_alter_taskelectricalmodel_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_execution',
            field=models.CharField(blank=True, max_length=10, verbose_name='дата выполнения'),
        ),
    ]
