# Generated by Django 5.0.6 on 2025-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0014_alter_taskelectricalmodel_date_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_creation',
            field=models.CharField(default='16.06.2025', max_length=10, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_deadline',
            field=models.CharField(blank=True, max_length=10, verbose_name='на какое число'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_registration',
            field=models.CharField(default='16.06.2025', max_length=10, verbose_name='дата заявки'),
        ),
    ]
