# Generated by Django 5.0.6 on 2025-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApi', '0015_alter_taskelectricalmodel_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_creation',
            field=models.CharField(default='06.09.2025', max_length=10, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='taskelectricalmodel',
            name='date_registration',
            field=models.CharField(default='06.09.2025', max_length=10, verbose_name='дата заявки'),
        ),
    ]
